-- Create managers table
CREATE TABLE IF NOT EXISTS managers (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS IX_managers_username ON managers(username);
CREATE INDEX IF NOT EXISTS IX_managers_email ON managers(email);

-- Insert 15 managers with hashed passwords (password123)
-- Note: These passwords are hashed using SHA256. The actual hash will be generated by the application.
-- The seed data will be inserted by the DbSeeder when the application starts.




